version: '3'

services:
  app:
    container_name: fastapi_practice
    build: ./
    working_dir: /home
    volumes:
      - .:/home
    ports:
      - "9004:9004"
    command: uvicorn app.main:app --host 0.0.0.0 --port 9004 --reload
    